CREATE TABLE payee (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_no NUMBER NOT NULL,
    payee_name VARCHAR2(100) NOT NULL,
    payee_account_no NUMBER NOT NULL,
    payee_sort_code VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT account_no, name, password FROM accounts WHERE account_no = 12345001;


-- To update password (replace 'newpassword' with your desired password)
UPDATE accounts SET password = 'Acc@2025' WHERE account_no = 12345001;
COMMIT;

SELECT account_no, name, password FROM accounts WHERE account_no = 12345002;



-- To update password (replace 'newpassword' with your desired password)
UPDATE accounts SET password = 'User@2025' WHERE account_no = 12345002;
COMMIT;

SELECT account_no, password, LENGTH(password) FROM accounts WHERE account_no = 12345003;

Select * From accounts;


